### PR TITLE
Review reported Tasks

### LINKED ISSUE #34: Reviewing reported Tasks in the admin dashboard
### Bootstrap Academy username

Morpheus

### Contact Details

_No response_

### What browsers are you seeing the problem on?

Chrome

### Overview:
Our website facilitates user-generated quizzes and challenges. To maintain content quality, we allow users to report inappropriate or incorrect tasks. Admins then review these reports via the admin dashboard.

#### Problem Description:
In the admin dashboard, under the "Reported Tasks" section, while I can view details about the report itself (Reported By, Reason, Comment, Reported At, Actions), the information about the task's creator (the user who was reported) is missing.

#### Expected Behavior:
The creator of the reported task should be prominently displayed within the "Reported Tasks" section to identify the user in question.

#### Acceptance Criteria:
- [x] The "Reported Tasks" section should have an additional column/field displaying the creator of each reported task.

---

#### Problem Description:
Upon navigating to the details of a specific report, the information displayed seems incomplete and incorrect.

1. Essential report details (Reported By, Reason, Comment, Reported At, and Creator of the task) are not visible.
2. Under "Options", the original quiz answer options ("One", "Two", "Three", "Four") are appended with filler "Lorem ipsum" text, indicating a frontend bug.
3. The action buttons ("Incorrect" and "Correct") are inadequate for comprehensive report management.

#### Expected Behavior:
1. All essential report details should be visible on the report details page.
2. The original quiz answer options should be displayed without any appended text.
3. Additional action buttons should be present: "Delete Task", "Adjust Task", "Ban Creator", and "Ban Reporter".

#### Acceptance Criteria:
- [x] The report details page should display all essential report details.
- [x] The "Options" section should only display the original quiz answer options without any additional text.
- [x] Introduce new action buttons as described above.

---

#### Problem Description:
Currently, after taking action on a report (Correct/Incorrect), the report disappears from the dashboard, making it inaccessible for future reference.

#### Expected Behavior:
Processed reports should not be deleted. Instead, they should be archived and displayed in a greyed-out format at the bottom of the "Reported Tasks" section. Admins should also have the option to filter and view either fresh reports or all reports, including the archived ones.

#### Acceptance Criteria:
- [ ] Processed reports should be archived and viewable in a greyed-out format.
- [ ] Introduce a filter option for viewing fresh reports and all reports (including archived ones).

### PR DESCRIPTION
**Pull request by StackSurfer**
### Issue 1: Missing Task Creator Information

- [x] The "Reported Tasks" section should have an additional column/field displaying the creator of each reported task.

### Issue 2: Report Details Page - Missing & Incorrect Information

- [x] The report details page should display all essential report details. (Reported By, Reason, Comment, Reported At, and Creator of the task)
    - [x] Multiple-Choice-Question 
    - [x] Coding-Challenge
    - [x] Question
    - [x] Matching
    
- [x] Locales for added essential report details    
    
- [ ] The "Options" section should only display the original quiz answer options without any additional text.
    - [x] Multiple-Choice-Question 
    - [x] Coding-Challenge
    - [ ] Question -> have not added a component because this is not available yet
    - [x] Matching

- [x] Introduce new action buttons as described above. ("Delete Task", "Adjust Task", "Ban Creator", and "Ban Reporter".)
- [x] Locales for new Buttons
### Issue 3: Report Archiving and Revisiting

> - [ ] Processed reports should be archived and viewable in a greyed-out format.

> - [ ] Introduce a filter option for viewing fresh reports and all reports (including archived ones).

### Problems with solving Issue 3 in the Frontend
After resolving a reported task, this task is no longer returned from [getReportetTaskList()](https://api-test.bootstrap.academy/challenges/redoc#tag/Subtasks/paths/~1subtask_reports/get). It would be beneficial if these tasks still appeared in the list but with an additional key indicating their report state. Additionally, it would be useful to incorporate a query parameter in the [get](https://api-test.bootstrap.academy/challenges/redoc#tag/Subtasks/paths/~1subtask_reports/get) call, allowing for the retrieval of either 'open', 'resolved', or 'all' reported tasks.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Translation updates (fix/improve or add new translations)

Fixes Bootstrap-Academy/Bootstrap-Academy#34

My Bootstrap Academy username:

### CODE REVIEW

**Comment by StackSurfer** [comment]
I just tried to report "coding-challenges". But theres 1. no report button and 2. I get responses of "not authorized" || "permission_denied" when reporting it in SwaggerUI even tough I'm authorized in with bearer. (tried it with admin & normal-user, before solving and after)

**Comment by Defelo** [comment]
Have you solved the subtask before trying to report it? Currently this is a requirement, but we might have to rethink that later

**Comment by StackSurfer** [comment]
> Have you solved the subtask before trying to report it? Currently this is a requirement, but we might have to rethink that later

Yes I did solve it with 2 accounts and tried to report it but that did not work

**Comment by Defelo** [comment]
Did you rate the subtask after solving it? Because at the moment you can only rate or report it, but not both (probably also needs to be changed later)

**Comment by StackSurfer** [comment]
> Did you rate the subtask after solving it? Because at the moment you can only rate or report it, but not both (probably also needs to be changed later)

I have not found any ability to rate or report a coding-challenge with the current UI

**Comment by Defelo** [comment]
Ok, then it is probably not implemented yet. Could you post the exact http request you are sending to the backend to report the coding challenge (you can just copy paste the curl command from swagger)? And also the response please?

**Comment by StackSurfer** [comment]
Yes sure!
request:
`{
	"POST": {
		"scheme": "https",
		"host": "api-test.bootstrap.academy",
		"filename": "/challenges/subtask_reports",
		"remote": {
			"Address": "[2a06:98c1:3121::3]:443"
		}
	}
}`
Body:
`{
	"comment": "test report coding-challenge",
	"reason": "ABUSE",
	"subtask_id": "617284ef-cb4a-456c-86b6-c7e422801812",
	"task_id": "55e96838-2ac6-419a-9d26-449ba4638840"
}`
response:
`{
	"error": "permission_denied"
}`

**Comment by StackSurfer** [comment]
@Defelo Are there new Code-style guidelines because that check failed?

**Comment by Defelo** [comment]
Yes, we recently added eslint to enforce a consistent code style (#51). You should be able to fix most (if not all) of these errors with `eslint --fix --ext .js,.vue,.ts .`

**Review by Defelo — APPROVED** [review]

**Pull request merged**
