### PR TITLE
Improve users page in admin dashboard

### LINKED ISSUE #41: Improve users page in admin dashboard
Fix and improve the user administration page on https://bootstrap-academy-admin.pages.dev/dashboard/users.

### Search
Currently it is only possible to search by email, not by username. There is also a bug which causes the same users to appear more than once when searching repeatedly using the same search term.

image

### Pagination
Replace the "load more" button with a pagination menu. Pagination works by splitting the list of users into smaller chunks (pages), all of the same size. For example, if the page size is 20, the first 20 users (user 1-20) are on the first page, user 21-40 on the second page, user 41-60 on the third, and so on. There should be a pagination menu, consisting of buttons to allow navigation between the different pages.

An example for a pagination menu:
image

### Filters
It is already possible to filter the user list, to display for example only users with 2FA enabled, but the current implementation is very limiting, since it allows only one filter at once. This should be changed to allow more complex queries, for example to only display enabled user accounts, that also have admin privileges, but do not have 2FA enabled (this kind of query is not possible with the current implementation).

## Acceptance criteria
- [x] The admin can select whether to search by username or by email.
- [x] Instead of the "load more" button, there is a pagination menu.
    - [x] The total number of (matching) users and the number of users on the current page are displayed.
    - [x] There are buttons for the 5 pages closest to the current page.
    - [x] There are buttons to go to the next/previous page.
    - [x] There are buttons to jump to the first/last page.
    - [x] It is possible to select the page size (10/20/50/100).
- [x] There are additional (composable) filters to only display...
    - [x] enabled/disabled users
    - [x] normal/admin users
    - [x] users with 2FA enabled/disabled
    - [x] verified/unverified users
    - [x] users who are / are not subscribed to the newsletter

### PR DESCRIPTION
**Pull request by StackSurfer**
## Description

- remove unnecessary console.log's -> better overview while working with own console.log's
- Add user types
- Implement a functional search by name or email.
- Fix the bug that caused repeated users in the table.
- add server-side Pagination
- add server-side Filter

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
Had to edit Search.vue component -> applied the required changes everywhere this component is used
- [x] Translation updates (fix/improve or add new translations)

Fixes Bootstrap-Academy/Bootstrap-Academy#41

My Bootstrap Academy username: Joggl
Screenshot 2023-10-29 at 00 23 13
Screenshot 2023-10-29 at 00 23 41
Screenshot 2023-10-29 at 00 24 07

### CODE REVIEW

**Review by Defelo — CHANGES_REQUESTED** [review]
Hi, thanks a lot for this pull request! I think the only thing that is still incomplete is the ability to compose filters. Currently it is only possible to select one filter at a time (e.g. display all administrators), but as described in [#41](https://github.com/Bootstrap-Academy/Bootstrap-Academy/issues/41), it would be nice if we could also compose these filters (e.g. display all administrators that don't have 2fa enabled). Here is an example of what this could look like (basically we just have one independent dropdown menu for each property):
image

Also some of the column headings are incorrect, e.g. "Normale Benutzer" instead of just "User" or "Benutzer" and "Headings.Enabled" instead of "Enabled":
image

**Comment by StackSurfer** [comment]
> Hi, thanks a lot for this pull request! I think the only thing that is still incomplete is the ability to compose filters. Currently it is only possible to select one filter at a time (e.g. display all administrators), but as described in [#41](https://github.com/Bootstrap-Academy/Bootstrap-Academy/issues/41), it would be nice if we could also compose these filters (e.g. display all administrators that don't have 2fa enabled). Here is an example of what this could look like (basically we just have one independent dropdown menu for each property): image
> 
Hello @Defelo! For clarification, would you like:

1. One dropdown menu to choose a user type (Admin, "normal" User, or Admin & User) and one dropdown menu for all other filters (Newsletter, 2FA, etc.), with only one value allowed per dropdown menu?

or 

2. One dropdown menu with one of the user types (Admin, User, or Admin & User) and one select area with the ability to select multiple values for all other filters?


> Also some of the column headings are incorrect, e.g. "Normale Benutzer" instead of just "User" or "Benutzer" and "Headings.Enabled" instead of "Enabled": image

Okay, I will replace "Normale Benutzer" with "User" and "Enabled"-related bug with "Enabled". Is that correct? 

I will try to apply these changes by Wednesday evening.

**Comment by Defelo** [comment]
> For clarification, would you like:
> 
> 1. One dropdown menu to choose a user type (Admin, "normal" User, or Admin & User) and one dropdown menu for all other filters (Newsletter, 2FA, etc.), with only one value allowed per dropdown menu?
> 
> or
> 
> 2. One dropdown menu with one of the user types (Admin, User, or Admin & User) and one select area with the ability to select multiple values for all other filters?

Actually neither, since we have five properties ("user"/"admin", "enabled"/"disabled", "2fa enabled" / "2fa disabled", "verified"/"unverified" and "subscribed to newsletter" / "not subscribed to newsletter"), we would need **five** independent dropdown menus, each with **three** options:
1. "Users" / "Admins" / no filter
2. "Enabled" / "Disabled" / no filter
3. "2FA enabled" / "2FA disabled" / no filter
4. "Verified" / "Unverified" / no filter
5. "Subscribed to newsletter" / "Not subscribed to newsletter" / no filter

The idea is that I can select any combination of these filters (e.g. "Users, Enabled, 2FA disabled, Unverified, (no filter for newsletter)" or "Admins, Enabled, (no filter for 2fa), (no filter for verified), Not subscribed to newsletter"), and only those users that match all of the selected filters are displayed.

> Okay, I will replace "Normale Benutzer" with "User" and "Enabled"-related bug with "Enabled". Is that correct?

Yes, that is correct.

> I will try to apply these changes by Wednesday evening.

Perfect, thanks again!

**Comment by StackSurfer** [comment]
Hello @Defelo 

I replaced the old Filter-dropdown with a new button that opne's a Modal where you can select the filter in any combination, and a "clearFilter" button. I hope that's fine.

Screenshot 2023-11-01 at 13 12 08

**Comment by Defelo** [comment]
Yes, that looks great, thank you!

**Review by Defelo — APPROVED** [review]

**Pull request merged**
